---
- name: "Install firewalld"
  ansible.builtin.package:
    name: firewalld
    state: present
  when: freeipa_server_install_firewalld | bool
  tags: firewall

- name: "Open firewall ports"
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ freeipa_server_firewalld_ports }}"
  notify: Reload firewalld
  when: freeipa_server_configure_firewalld | bool
  tags: firewall
