---
- name: "Install firewalld"
  ansible.builtin.package:
    name: firewalld
    state: present

- name: "Open firewall ports"
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ freeipa_server_firewalld_ports }}"
  notify: Reload firewalld
