---
- name: "Import asserts tasks"
  ansible.builtin.import_tasks: asserts.yml

- name: "Import firewalld tasks"
  ansible.builtin.import_tasks: firewalld.yml
  when: freeipa_server_configure_firewalld | bool

- name: "Install rng-tools for better entropie"
  ansible.builtin.package:
    name: rng-tools
    state: present

- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ freeipa_packages }}"
    state: present
  register: freeipa_install

- name: "Install tasks"
  when: freeipa_install.changed or freeipa_server_force_install|bool
  block:
    - name: "MASTER - Configure FreeIPA server (take a while )"
      ansible.builtin.shell: "umask 0022 && ipa-server-install --unattended {{ freeipa_server_install_options | join(' ') }}"
      changed_when: false
      when:
        - freeipa_server_type == 'master'
      notify: Restart ipa services

    - name: "REPLICA 1/3 - Install ipa client"
      ansible.builtin.command: "ipa-client-install --unattended --server={{ freeipa_server_master_fqdn }} {{ freeipa_client_install_options | join(' ') }}"
      changed_when: false
      when:
        - freeipa_server_type == 'replica'

    - name: "REPLICA 2/3 - add to ipservers group"
      ansible.builtin.command: "ipa hostgroup-add-member ipaservers --hosts {{ ansible_fqdn }}"
      changed_when: false
      failed_when: false
      delegate_to: "{{ freeipa_server_master_fqdn }}"
      when:
        - freeipa_server_type == 'replica'

    - name: "REPLICA 3/3 - Install replica (take a while)"
      ansible.builtin.command: "umask 0022 && ipa-replica-install --unattended --server={{ freeipa_server_master_fqdn }} {{ freeipa_replica_install_options | join(' ') }}"
      changed_when: false
      when:
        - freeipa_server_type == 'replica'

#- name: "Replace ipa-rewrite"
#  ansible.builtin.template:
#    src: ipa-rewrite.conf.j2
#    dest: /etc/httpd/conf.d/ipa-rewrite.conf
#    mode: 0644
#  notify: Ipa restart

## Verif
- name: "Global - Ensure admin config / auth to Kerberos realm"
  ansible.builtin.shell: |
    set -o pipefail
    echo '{{ freeipa_server_admin_password }}' | kinit admin
  changed_when: false

#ipactl status
