---
- name: "Prepare host"
  when: freeipa_server_configure_hostname
  block:
    - name: "Ensure valid hostname"
      ansible.builtin.hostname:
        name: "{{ freeipa_server_hostname }}"

    - name: "Ensure hostname resolve to ip and not localhost"
      ansible.builtin.replace:
        path: '{{ freeipa_server_hosts_path }}'
        regexp: '^127.0.0.1(\s+.*)?$'
        replace: '{{ ansible_default_ipv4.address }}\1 {{ freeipa_server_hostname }}'

- name: "Ensure ipv6 is not disable"
  ansible.builtin.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '0'
    sysctl_set: true
    state: present
    reload: true
  when: freeipa_server_configure_ipv6

- name: "Install rng-tools for better entropie"
  ansible.builtin.package:
    name: rng-tools
    state: present
