---
- name: Restart ipa services
  ansible.builtin.service:
    enabled: true
    name: ipa
    state: restarted

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Ipa restart
  ansible.builtin.command: ipactl restart
  changed_when: false
