---
- name: restart ipa services
  ansible.builtin.service:
    enabled: true
    name: ipa
    state: restarted

- name: reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
